wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.19
    start_time: 1712600271.302976
    t:
      1:
      - 1
      - 30
      - 55
      3:
      - 23
      4: 3.8.19
      5: 0.13.11
      8:
      - 5
